# Generated by Django 5.1.3 on 2024-11-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(default="", max_length=255)),
                ("title", models.CharField(default="", max_length=255)),
                ("year", models.DateField(default=None)),
                ("publisher", models.CharField(default="", max_length=255)),
                ("isbn", models.CharField(max_length=13)),
            ],
        ),
    ]
