# Generated by Django 5.1.3 on 2024-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_author_publisher_rename_year_book_publish_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="author",
            name="middle_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
