# Generated by Django 5.1.3 on 2024-11-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_author_email_alter_publisher_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="edition",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
