# Generated by Django 5.1.3 on 2024-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_book_discount_book_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=255)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_name", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("membership", models.BooleanField(default=False)),
            ],
        ),
    ]
