# Generated by Django 5.1.3 on 2024-11-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_flightplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightplan",
            name="destination",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="flightplan",
            name="origin",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="flightplan",
            name="flightnum",
            field=models.TextField(default=""),
        ),
    ]
