# Generated by Django 5.1.3 on 2024-11-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_flightplan_destination_flightplan_origin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
                ("state", models.CharField(default="", max_length=2)),
                ("zip", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="year",
            new_name="publish_date",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="", max_length=13),
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="api.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.publisher"
            ),
        ),
    ]
