# Generated by Django 5.1.3 on 2024-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_author_email_author_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
