# Generated by Django 5.1.3 on 2024-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_book_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
