# Generated by Django 5.1.3 on 2024-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_reader"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="zip",
            new_name="postcode",
        ),
        migrations.AddField(
            model_name="publisher",
            name="country",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
